[package]
edition = "2021"
name = "util_datetime"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
log = "0.4.19"
util_error = {version = "0", path = "../util_error", features = ["chrono"]}
