[workspace]
resolver = "2"
members = [
  "util_datetime",
  "util_email",
  "util_error",
  "util_response",
  "util_from_primitive",
  "util_meilisearch",
  "util_postgres",
  "util_redis",
  "util_sqlite",
  "util_fluvio",
]
