[package]
name = "util_email"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = { version = "0.10.4", features = ["tokio1-native-tls"] }
log = "0.4.19"
once_cell = "1.18.0"

